USE [master]
GO
/****** Object:  Database [QLDH]    Script Date: 4/14/2024 1:31:53 AM ******/
CREATE DATABASE [QLDH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLDH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QLDH.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLDH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QLDH_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QLDH] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLDH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLDH] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLDH] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLDH] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLDH] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLDH] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLDH] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QLDH] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLDH] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLDH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLDH] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLDH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLDH] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLDH] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLDH] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLDH] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QLDH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLDH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLDH] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLDH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLDH] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLDH] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLDH] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLDH] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QLDH] SET  MULTI_USER 
GO
ALTER DATABASE [QLDH] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLDH] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLDH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLDH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QLDH] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QLDH] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QLDH] SET QUERY_STORE = ON
GO
ALTER DATABASE [QLDH] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO
USE [QLDH]
GO
/****** Object:  Table [dbo].[DonHang]    Script Date: 4/14/2024 1:31:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DonHang](
	[idDH] [varchar](10) NOT NULL,
	[idSP] [varchar](10) NULL,
	[idKH] [varchar](10) NULL,
	[SoLuong] [int] NULL,
	[Gia] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[idDH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KhachHang]    Script Date: 4/14/2024 1:31:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KhachHang](
	[idKH] [varchar](10) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[NgaySinh] [varchar](10) NULL,
	[Phone] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[idKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhaCungCap]    Script Date: 4/14/2024 1:31:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhaCungCap](
	[idNCC] [varchar](10) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Phone] [varchar](10) NULL,
	[DiaChi] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[idNCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SanPham]    Script Date: 4/14/2024 1:31:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SanPham](
	[idSP] [varchar](10) NOT NULL,
	[idNCC] [varchar](10) NULL,
	[Name] [nvarchar](50) NULL,
	[Mota] [nvarchar](50) NULL,
	[Gia] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[idSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TaiKhoan]    Script Date: 4/14/2024 1:31:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaiKhoan](
	[TenTaiKhoan] [varchar](50) NOT NULL,
	[MatKhau] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[TenTaiKhoan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [QLDH] SET  READ_WRITE 
GO
